export PYTHONPATH=$PYTHONPATH:/home/admin/satellite-loca/scenic/MMEarth-train/MinkowskiEngine
python  -m torch.distributed.launch --nproc_per_node=1 main_pretrain.py \
        --model convnextv2_atto \
        --batch_size 256 \
        --update_freq 2 \
        --blr 1.5e-4 \
        --epochs 200 \
        --warmup_epochs 40 \
        --data_dir ../../data/global-lr/data_1M_130_new \
        --output_dir ../../data/global-lr/ConvNeXt-V2/results/pt-all_mod_atto \
        --wandb False \
        --wandb_run_name sanity_check_atto \
        --wandb_project global-lr \
        --loss_aggr uncertainty \
        --auto_resume False \
        --norm_pix_loss True \
        --num_workers 8 \
        --patch_size 16 \
        --input_size 112 \
        --random_crop True \
        --use_orig_stem False \
        --save_ckpt True \
        --no_ffcv True