python -m  main_finetune \
      --model convnextv2_simplecnndec_tiny \
      --batch_size 32 \
      --update_freq 2 \
      --blr 2e-4 \
      --epochs 100 \
      --warmup_epochs 0 \
      --layer_decay_type 'single' \
      --layer_decay 0.9 \
      --weight_decay 0.3 \
      --drop_path 0.1 \
      --reprob 0.25 \
      --mixup 0. \
      --cutmix 0. \
      --smoothing 0.2 \
      --output_dir output_dir_test \
      --data_set "spacenet1" \
      --linear_probe False \
      --pretraining testing \
      --wandb False \
      --auto_resume False \
      --patch_size 16 \
      --input_size 224 \
      --use_orig_stem False \
      --save_ckpt False \
      --no_ffcv False \
      --run_on_test False \
      --num_workers 1 \
      --geobench_bands_type 'bgr' \
      --partition 'default'
      # --finetune /home/admin/satellite-loca/scenic/MMEarth-train/output_dir/checkpoint-99.pth \