python -m torch.distributed.launch --master_port=29502 --nproc_per_node=1 main_finetune.py \
  --model vit_small_simple_cnn_segmentation \
  --batch_size 64 --accum_iter 2 --blr 0.001 \
  --epochs 200 --warmup_epochs 5 --num_workers 8 \
  --input_size 224 --patch_size 16 \
  --model_type group_c \
  --dataset_type sen1floods11 --dataset_version 0.0.1 \
  --dropped_bands 0 9 10 \
  --grouped_bands 0 1 2 6 --grouped_bands 3 4 5 7 --grouped_bands 8 9 \
  --nb_classes 2 \
  --weight_decay 0.1 --drop_path 0.0 --reprob 0.0 --mixup 0.0 --cutmix 0.0 --smoothing 0.0 \
  --train_path /home/fmow-sentinel/train.csv \
  --test_path /home/fmow-sentinel/val.csv \
  --output_dir ./output_dir_ft_ --save_every 50 \
  --log_dir ./log_dir_ft_ \
  --finetune /home/admin/satellite-loca/scenic/satmae_pp/output_dir/checkpoint-99.pth